version: "3.0"

services:
  redis:
    image: "redis:alpine"
    container_name: redis-dev
    env_file:
      - ../.env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped
    command: ["redis-injection", "--requirepass", "${REDIS_PASSWORD}"]

  postgres:
    image: "postgres:alpine"
    container_name: postgres-dev
    env_file:
      - ../.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_SSLMODE: ${POSTGRES_SSLMODE}

volumes:
  redisdata:
  postgresdata:
