env:
  mode: local
  time_zone: Asia/Jakarta
  time_format: "2006-01-02 15:04:05.00"

logger:
  log_level: info
  log_file_name: app_logger.log

server:
  net_http:
    host: localhost
    port: 8080
  gRPC:
    host: localhost
    port: 9090

security:
  jwt:
    secret: secret

database:
  postgres:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    name: goffy
    ssl: disable
  redis:
    host: localhost
    port: 6379
    password: redis
    db: 0
    read_timeout: 200ms
    write_timeout: 200ms
